### ISSUE TITLE
Permisos de escritura

### ISSUE THREAD

**Issue by carmenmquz** [2DAW-CarlosIII/marcaPersonalFront#2]
¡Hola!
Acabo de darme cuenta que no me permite hacer el pull request. Por si podríamos revisar los permisos, para que todos podamos acceder al código desde el repo común.
¡Gracias!

**Comment by albsierra** [comment]
Ya disponéis de permisos de escritura, por lo que ya deberíais poder crear y aprobar los PULL REQUEST en el repositorio del front.
