### ISSUE TITLE
instalar react-bootstrap

### ISSUE THREAD

**Issue by albsierra** [2DAW-CarlosIII/marcaPersonalFront#6]
Para poder utilizar componentes como el que se referencia [aquí](https://github.com/2DAW-CarlosIII/marcaPersonalFront/blob/98c4bdc3efa7fd119e15380f0370fee76116cd5e/src/Front/components/common/Navbar.jsx#L3), es necesario que el paquete react-bootstrap esté instalado.

Posiblemente, lo habéis instalado con `npm install react-bootstrap`, pero eso únicamente hace la instalación en local y cuando otro desarrollador hace un `npm install` ese paquete no se instala porque no está en el `package.json`.

Para conseguir que el paquete se referencie también en el `package.json` necesitáis instalar con
`npm install --save react-bootstrap`.

**Comment by carmenmquz** [comment]
Copy! Lo corrijo enseguida y lo subo en el siguiente commit.
